#!/bin/sh

#Script to look at simple report file generated by manifest checker - if zero missing files found in target directory it will generate a tar of the target directory (per JD)

if [ $# != 2 ]
then
	echo "Usage: <target report file> <directory to write tar file in>"
	exit
fi

target_report=$1
tar_target_dir=$2

#work out the parameters from the file
if [ -f $target_report ]
then

	#data
	data_triple=`head -1 $target_report |  awk '{print $1}' | tr ':' '\t'`

	type=`echo $data_triple | awk '{print $1}'`
	num=`echo $data_triple | awk '{print $2}'`
	dir=`echo $data_triple | awk '{print $3}'`
	
	if [ "$num" = "0" ]
	then
		tarfilename=`basename $target_report | cut -c1-12 | sed 's/$/\.tar.gz/' `
		tarfile=`echo "${tar_target_dir}/${tarfilename}"`
		command=`echo "tar czPf ${tarfile} ${dir}"`
		echo "Attempting to create backup tar file: ${tarfile}...."
		exec $command

		#wait for it to complete
		if [ -f $tarfile ] 
		then
			echo "${tarfile} has been successfully created!"
		else
			echo "Could not generate ${tarfile}"
			exit
		fi
	else
		echo "ERROR: cannot create tar file as missing files ($num)"
	fi
else
	echo "${target_report} does not exist"
	exit
fi
